bmstu_project/bmstu_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from student import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^student/', include('student.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/register/$', views.StudentRegistrationView.as_view(), name='registration_register'),
    url(r'^accounts/', include('registration.backends.simple.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bmstu_project/student/urls.py
from django.conf.urls import url
from student import views


urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^majors/$', views.majors_list, name='majors_list'),
	url(r'^add_major/$', views.add_major, name='add_major'),
	url(r'^register_profile/$', views.register_profile, name='register_profile'),
	url(r'^profile/(?P<username>[\w\-]+)/$', views.profile, name='profile'),
	url(r'^profiles/$', views.profiles_list, name='profiles_list'),
	url(r'^print/report/$', views.report_document, name='report_document'),
	url(r'^print/grade/$', views.grade_document, name='grade_document'),
]

bmstu_project/student/models.py
from django.db import models
from django.contrib.auth.models import User


class Major(models.Model):
	"""
	Major of students
	Ex: IU7 - Kỹ thuật phần mềm - Software Engineering
	"""
	code = models.CharField(max_length=20, blank=False, unique=True)
	# Vietnamese Name of Major
	viName = models.CharField(max_length=128, blank=False, unique=True)
	# English Name of Major
	enName = models.CharField(max_length=128, blank=False, unique=True)


	class Meta:
		verbose_name_plural = 'majors'


	def __str__(self):
		return self.code


class UserProfile(models.Model):
	user = models.OneToOneField(User, primary_key=True, on_delete=models.CASCADE)
	major = models.ForeignKey(Major, on_delete=models.CASCADE, blank=False)
	fullName = models.CharField(max_length=128, blank=False)
	gender = models.CharField(max_length=20, blank=False)
	birthday = models.DateField(blank=False)
	ethnic = models.CharField(max_length=20, blank=False)  # Dan toc
	religion = models.CharField(max_length=20, blank=False)  # Ton giao
	studyYear = models.IntegerField(blank=False)
	addressVN = models.CharField(max_length=128, blank=False)
	addressRu = models.CharField(max_length=128, blank=False)
	phone = models.CharField(max_length=128, blank=False)
	workPlace = models.CharField(max_length=128, blank=True)
	dateOfAdmission = models.DateField(blank=False)  # Ngay nhap hoc
	dateOfStudy = models.DateField(blank=False)  # Ngay bat dau khoa hoc
	timeOfStudy = models.CharField(max_length=128, blank=False)  # Thoi gian dao tao
	infoOfStudy = models.CharField(max_length=128, blank=False)  # Dang hoc hoc ki ?

	# Result of study
	ruSubject1 = models.CharField(max_length=128, blank=True)
	viSubject1 = models.CharField(max_length=128, blank=True)
	resultSubject1 = models.CharField(max_length=20, blank=True)

	ruSubject2 = models.CharField(max_length=128, blank=True)
	viSubject2 = models.CharField(max_length=128, blank=True)
	resultSubject2 = models.CharField(max_length=20, blank=True)

	ruSubject3 = models.CharField(max_length=128, blank=True)
	viSubject3 = models.CharField(max_length=128, blank=True)
	resultSubject3 = models.CharField(max_length=20, blank=True)

	ruSubject4 = models.CharField(max_length=128, blank=True)
	viSubject4 = models.CharField(max_length=128, blank=True)
	resultSubject4 = models.CharField(max_length=20, blank=True)

	ruSubject5 = models.CharField(max_length=128, blank=True)
	viSubject5 = models.CharField(max_length=128, blank=True)
	resultSubject5 = models.CharField(max_length=20, blank=True)

	ruSubject6 = models.CharField(max_length=128, blank=True)
	viSubject6 = models.CharField(max_length=128, blank=True)
	resultSubject6 = models.CharField(max_length=20, blank=True)

	ruSubject7 = models.CharField(max_length=128, blank=True)
	viSubject7 = models.CharField(max_length=128, blank=True)
	resultSubject7 = models.CharField(max_length=20, blank=True)

	ruSubject8 = models.CharField(max_length=128, blank=True)
	viSubject8 = models.CharField(max_length=128, blank=True)
	resultSubject8 = models.CharField(max_length=20, blank=True)

	ruSubject9 = models.CharField(max_length=128, blank=True)
	viSubject9 = models.CharField(max_length=128, blank=True)
	resultSubject9 = models.CharField(max_length=20, blank=True)

	ruSubject10 = models.CharField(max_length=128, blank=True)
	viSubject10 = models.CharField(max_length=128, blank=True)
	resultSubject10 = models.CharField(max_length=20, blank=True)

	ruSubject11 = models.CharField(max_length=128, blank=True)
	viSubject11 = models.CharField(max_length=128, blank=True)
	resultSubject11 = models.CharField(max_length=20, blank=True)

	ruSubject12 = models.CharField(max_length=128, blank=True)
	viSubject12 = models.CharField(max_length=128, blank=True)
	resultSubject12 = models.CharField(max_length=20, blank=True)

	# Information of Bank
	nameBank = models.CharField(max_length=128, blank=True)
	nameAccount = models.CharField(max_length=128, blank=True)  # Ten tai khoan tieng Nga


	def __str__(self):
		return self.user.username

bmstu_project/student/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from student.models import Major, UserProfile
from student.forms import MajorForm, UserProfileForm
from django.contrib.auth.decorators import login_required
from registration.backends.simple.views import RegistrationView
from django.urls import reverse
from django.contrib.auth.models import User
from docx import *
from io import BytesIO
from datetime import date
from docx.shared import Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH, WD_LINE_SPACING
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.shared import Cm, Inches, Mm


def index(request):
	context_dict = {'boldmessage': "Crunchy, creamy, cookie, candy, cupcake!"}

	return render(request, 'student/index.html', context=context_dict)

@login_required
def majors_list(request):
	majors_list = Major.objects.all()

	return render(request, 'student/majors_list.html',
		{'majors_list' : majors_list})

@login_required
def add_major(request):
    form = MajorForm()

    if request.method == 'POST':
        form = MajorForm(request.POST)

        if form.is_valid():
            form.save(commit=True)

            return index(request)
        else:
            print(form.errors)

    return render(request, 'student/add_major.html', {'form': form})

@login_required
def register_profile(request):
    form = UserProfileForm()

    if request.method == 'POST':
        form = UserProfileForm(request.POST)
        if form.is_valid():
            user_profile = form.save(commit=False)
            user_profile.user = request.user
            user_profile.save()

            return redirect('index')
        else:
            print(form.errors)

    context_dict = {'form':form}

    return render(request, 'student/profile_registration.html', context_dict)


class StudentRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return reverse('register_profile')

@login_required
def profile(request, username):
    try:
        user = User.objects.get(username=username)
    except User.DoesNotExist:
        return redirect('index')
    
    userprofile = UserProfile.objects.get_or_create(user=user)[0]
    form = UserProfileForm({
            'major': userprofile.major,
            'fullName': userprofile.fullName,
            'gender': userprofile.gender,
            'birthday': userprofile.birthday,
            'ethnic': userprofile.ethnic,
            'religion': userprofile.religion,
            'studyYear': userprofile.studyYear,
            'addressVN': userprofile.addressVN,
            'addressRu': userprofile.addressRu,
            'phone': userprofile.phone,
            'workPlace': userprofile.workPlace,
            'dateOfAdmission': userprofile.dateOfAdmission,
            'dateOfStudy': userprofile.dateOfStudy,
            'timeOfStudy': userprofile.timeOfStudy,
            'infoOfStudy': userprofile.infoOfStudy,

            'ruSubject1': userprofile.ruSubject1,
            'viSubject1': userprofile.viSubject1,
            'resultSubject1': userprofile.resultSubject1,

            'ruSubject2': userprofile.ruSubject2,
            'viSubject2': userprofile.viSubject2,
            'resultSubject2': userprofile.resultSubject2,

            'ruSubject3': userprofile.ruSubject3,
            'viSubject3': userprofile.viSubject3,
            'resultSubject3': userprofile.resultSubject3,

            'ruSubject4': userprofile.ruSubject4,
            'viSubject4': userprofile.viSubject4,
            'resultSubject4': userprofile.resultSubject4,

            'ruSubject5': userprofile.ruSubject5,
            'viSubject5': userprofile.viSubject5,
            'resultSubject5': userprofile.resultSubject5,

            'ruSubject6': userprofile.ruSubject6,
            'viSubject6': userprofile.viSubject6,
            'resultSubject6': userprofile.resultSubject6,

            'ruSubject7': userprofile.ruSubject7,
            'viSubject7': userprofile.viSubject7,
            'resultSubject7': userprofile.resultSubject7,

            'ruSubject8': userprofile.ruSubject8,
            'viSubject8': userprofile.viSubject8,
            'resultSubject8': userprofile.resultSubject8,

            'ruSubject9': userprofile.ruSubject9,
            'viSubject9': userprofile.viSubject9,
            'resultSubject9': userprofile.resultSubject9,

            'ruSubject10': userprofile.ruSubject10,
            'viSubject10': userprofile.viSubject10,
            'resultSubject10': userprofile.resultSubject10,

            'ruSubject11': userprofile.ruSubject11,
            'viSubject11': userprofile.viSubject11,
            'resultSubject11': userprofile.resultSubject11,

            'ruSubject12': userprofile.ruSubject12,
            'viSubject12': userprofile.viSubject12,
            'resultSubject12': userprofile.resultSubject12,

            'nameBank': userprofile.nameBank,
            'nameAccount': userprofile.nameAccount,
        })
    
    if request.method == 'POST':
        form = UserProfileForm(request.POST, instance=userprofile)
        if form.is_valid():
            form.save(commit=True)
            return redirect('profile', user.username)
        else:
            print(form.errors)
    
    return render(request, 'student/profile.html', 
            {'userprofile': userprofile, 'selecteduser': user, 'form': form})

@login_required
def profiles_list(request):
    userprofile_list = UserProfile.objects.all()

    return render(request, 'student/profiles_list.html',
            {'userprofile_list' : userprofile_list})

@login_required
def report_document(request):
    user_current = None
    if request.user.is_authenticated:
        user_current = UserProfile.objects.get(user=request.user.id)

    document = Document()
    docx_title='BCHT_BGD.docx'

    # Setting document
    style = document.styles['Normal']
    font = style.font
    font.name = 'Times New Roman'
    font.size = Pt(14)

    section = document.sections[0]
    section.page_height = Mm(297)
    section.page_width = Mm(210)
    section.top_margin = Inches(0.70)
    section.bottom_margin = Inches(0.70)
    section.left_margin = Inches(1.00)
    section.right_margin = Inches(1.00)

    # Content
    paragraph1 = document.add_paragraph()
    paragraph1.alignment = WD_ALIGN_PARAGRAPH.CENTER
    paragraph1.paragraph_format.line_spacing_rule = WD_LINE_SPACING.SINGLE
    paragraph1.add_run('CỘNG HÒA XÃ HỘI CHỦ NGHĨA VIỆT NAM').bold = True
    run = paragraph1.add_run('\nĐộc lập - Tự do - Hạnh phúc')
    run.font.bold = True
    run.font.underline = True
    paragraph1.add_run('\n\nBÁO CÁO TIẾN ĐỘ HỌC TẬP').bold = True
    paragraph1.add_run('\n(từ ngày  tháng  năm 20  đến ngày  tháng  năm 20  )')
    paragraph1.add_run('\n\nKính gửi: ')
    paragraph1.add_run('- Bộ Giáo dục và Đào tạo').bold = True

    paragraph2 = document.add_paragraph()
    paragraph2.alignment = WD_ALIGN_PARAGRAPH.LEFT
    paragraph2.paragraph_format.line_spacing_rule = WD_LINE_SPACING.SINGLE

    paragraph2.add_run('1. Họ và tên: ')
    paragraph2.add_run(user_current.fullName).bold = True
    paragraph2.add_run('\t\t\t\t\tNam/nữ: ')
    paragraph2.add_run(user_current.gender).bold = True

    paragraph2.add_run('\n2. Ngày sinh: ')
    paragraph2.add_run(user_current.birthday.strftime('%d.%m.%Y')).bold = True

    paragraph2.add_run('\n3. Dân tộc: ')
    paragraph2.add_run(user_current.ethnic).bold = True
    paragraph2.add_run('\t\t\t\t\t\t\tTôn giáo: ')
    paragraph2.add_run(user_current.religion).bold = True

    paragraph2.add_run('\n4. Năm trúng tuyển (đối với lưu học sinh học bổng): ')
    paragraph2.add_run(str(user_current.studyYear)).bold = True
    paragraph2.add_run('. Năm đi học: ')
    paragraph2.add_run(str(user_current.studyYear)).bold = True

    paragraph2.add_run('\n5. Địa chỉ nơi ở tại Việt Nam: ')
    paragraph2.add_run(user_current.addressVN).bold = True

    paragraph2.add_run('\n6. Cơ quan công tác (nếu có): ')
    if user_current.workPlace:
        paragraph2.add_run(user_current.workPlace).bold = True

    paragraph2.add_run('\n7. Diện học bổng (Hiệp định/NSNN/Khác, ghi cụ thể): ')
    paragraph2.add_run('Hiệp định').bold = True

    paragraph2.add_run('\n8. Ngành học ở nước ngoài (ghi tiếng Việt và tiếng Anh):\n')
    paragraph2.add_run('    ' + user_current.major.viName).bold = True
    paragraph2.add_run(' (' + user_current.major.enName + ')').bold = True

    paragraph2.add_run('\n9. Tên và địa chỉ trường học ở nước ngoài (ghi tiếng Việt và tiếng Anh): ')
    paragraph2.add_run('\n    Trường Đại Học Kỹ Thuật Tổng Hợp Bauman\n    (Bauman Moscow State Technical University)').bold = True

    paragraph2.add_run('\n10. Ngày đến trường nhập học: ')
    paragraph2.add_run(user_current.dateOfAdmission.strftime('%d.%m.%Y')).bold = True

    paragraph2.add_run('\n11. Ngày bắt đầu khóa học (theo thông báo của trường): ')
    paragraph2.add_run(user_current.dateOfStudy.strftime('%d.%m.%Y')).bold = True

    paragraph2.add_run('\n12. Thời gian đào tạo (theo thông báo của trường): ')
    paragraph2.add_run(user_current.timeOfStudy).bold = True

    paragraph2.add_run('\n13. Đang học học kỳ mấy, thời gian còn lại: ')
    paragraph2.add_run(user_current.infoOfStudy).bold = True

    paragraph2.add_run('\n14. Địa chỉ nơi ở nước ngoài: ')
    paragraph2.add_run(user_current.addressRu).bold = True

    paragraph2.add_run('\n15. E-mail ở nước ngoài: ')
    paragraph2.add_run(request.user.email).bold = True

    paragraph2.add_run('\n16. Điện thoại liên hệ ở nước ngoài: ')
    paragraph2.add_run(str(user_current.phone)).bold = True

    GRADE_CHOICES = {
        "Отлично": "Giỏi",
        "Хорошо": "Khá",
        "Удовлетворительно": "Trung Bình",
        "Зачтено": "Đạt"
    }

    paragraph2.add_run('\n17. Kết quả học tập:')

    table1 = document.add_table(rows=1, cols=2)
    table1.columns[0].width=Inches(4.3)
    table1.columns[1].width=Inches(2)
    row = table1.rows[0]

    if user_current.ruSubject1:

bmstu_project/templates/student/add_major.html
{% extends 'student/base.html' %}
{% load static %}

{% block title %}
    Add Major
{% endblock %}

{% block body_block %}
    <hr/>
    <h3 class="font-weight-normal">Add a Major</h3>
    <hr/>

    <form id="major_form" method="post" action="{% url 'add_major' %}">  
        {% csrf_token %}

        {% if form.errors %}
            {% for field in form %}
                {% for error in field.errors %}
                    <div class="alert alert-danger">
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endif %}

        <div class="form-group row">
            <label class="col-form-label col-sm-2 font-weight-bold">Code</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="id_code" name="code" placeholder="IU7..." required/>
            </div>
        </div>

        <div class="form-group row">
            <label class="col-form-label col-sm-2 font-weight-bold">Vietnamese Name</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="id_viName" name="viName" placeholder="Kỹ thuật phần mềm..." required/>
            </div>
        </div>

        <div class="form-group row">
            <label class="col-form-label col-sm-2 font-weight-bold">English Name</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="id_enName" name="enName" placeholder="Software Engineering..."required/>
            </div>
        </div>

        <hr/>

        <div class="text-left">
            <input class="btn btn-primary btn-sm" type="submit" name="submit" value="Save" />
        </div>
    </form>
{% endblock %}

bmstu_project/templates/student/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
	<head>
		<meta name="viewport" content="width=device-width, initial-scale=1">
	    <meta charset="UTF-8">
	    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.9/angular.min.js"></script>
	    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.9/angular-route.js"></script>
	    <meta name="viewport" content="width=device-width, initial-scale=1">
	    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	    <link href="/static/css/album.css" type="text/css" rel="stylesheet">

		<link rel="icon" href="{% static 'images/bmstu.png' %}">
		<title>
			{% block title %}BMSTU{% endblock %}
		</title>
	</head>

	<body>
		<header>
			<nav class="navbar navbar-expand navbar-dark flex-column flex-md-row bd-navbar" style="background-color: #1C2833">
				<div class="collapse navbar-collapse" id="navbar">
					<ul class="navbar-nav mr-auto">
						<li class="nav-item active">
							<a class="nav-link" href="{% url 'index' %}">Home</a>
						</li>
						{% if user.is_authenticated %}
			            <!-- <li class="nav-item">
			              <a class="nav-link" href="{% url 'majors_list' %}">Major</a>
			            </li> -->
			            <!-- <li class="nav-item">
			              <a class="nav-link" href="{% url 'profiles_list' %}">User</a>
			            </li> -->
			            <li class="nav-item">
			              <a class="nav-link" href="{% url 'profile' user.username %}">Profile</a>
			            </li>
						{% endif %}
					</ul>

					<ul class="navbar-nav">
						{% if user.is_authenticated %}
						<li class="nav-item">
							<a class="nav-link" href="{% url 'auth_logout' %}?next=/student/">Logout</a>
						</li>
						{% else %}
						<li class="nav-item">
							<a class="nav-link" href="{% url 'registration_register' %}">Sign Up</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{% url 'auth_login' %}">Login</a>
						</li>
						{% endif %}
					</ul>
				</div>
			</nav>
		</header>

		<main role="main" class="container">
			{% block body_block %}{% endblock %}
		</main>

		<footer class="footer">
	      <div class="container">
	        <span class="text-muted">Copyright &copy; Made by Hama</span>
	      </div>
	    </footer>

		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
	</body>
</html>

bmstu_project/templates/student/index.html
{% extends 'student/base.html' %}
{% load static %}

{% block title %}
	Home
{% endblock %}

{% block body_block %}
	{% if user.is_authenticated %}
		<h1>Hello {{ user.username }}!</h1>
	{% else %}
		<h1>Hello anonymous! </h1>
	{% endif %}

	<hr/>

	<p class="lead">Trang web nhằm mục đích giúp các bạn sinh viên tạo file Báo cáo học tập và Bản dịch bảng điểm dưới dạng Word.</p>
	<p class="lead">Hướng dẫn sử dụng:</p>
	<p>- Bước 1: Đăng ký tài khoản: Nhấn phím "Sign Up".</p>
	<p>- Bước 2: Đăng nhập bằng tài khoản đã đăng ký: Nhấn phím "Login".</p>
	<p>- Bước 3: Vào trang thông tin bản thân: Nhấn phím "Profile".</p>
	<p>- Bước 4: Cập nhật thông tin bản thân: Nhập các thông tin cần thiết, nhấn phím "Cập nhật" để lưu thông tin.</p>
	<p>- Bước 5: In các tài liệu cần thiết: Vào "Profile", nhấn "Báo cáo" để in báo cáo học tập, nhấn "Bảng điểm" để in bản dịch bảng điểm, nhấn "Bảo hiểm" để in bản dịch bảo hiểm, nhấn "Hóa đơn bảo hiểm" để in bản dịch hóa đơn bảo hiểm.</p>
	<p class="lead">Lưu ý: Các file báo cáo chưa hoàn toàn đầy đủ, mọi người cần bổ sung các thông tin thêm!</p>
{% endblock %}

bmstu_project/templates/student/profile_registration.html
{% extends "student/base.html" %}
{% load static %}

{% block title %}
	Registration - Step 2
{% endblock %}

{% block body_block %}
    <h3 class="mb-4">Registration - Step 2</h3>

	<form method="post" action="." enctype="multipart/form-data">
		{% csrf_token %}

        {% if form.errors %}
            {% for field in form %}
                {% for error in field.errors %}
                    <div class="alert alert-danger">
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endif %}

		<div class="form-group row">
            <label class="col-form-label col-sm-2 font-weight-bold">Họ và tên</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="id_fullName" name="fullName" required />
            </div>
        </div>
		
		<div class="form-group row">
            <label class="col-form-label col-sm-2 font-weight-bold">Ngành học</label>
            <div class="col-sm-2">
	            <select id="id_major" name="major" class="form-control">
	            	{% for choice in form.major.field.queryset %}
	            		<option value={{ choice.pk }}>{{ choice }}</option>
					{% endfor %}
				</select>
			</div>

			<label class="col-form-label col-sm-2 font-weight-bold">Nam/Nữ</label>
            <div class="col-sm-2">
                <select id="id_gender" name="gender" class="form-control">
	            	{% for x, y in form.gender.field.choices %}
	            		<option value={{ x }}>{{ y }}</option>
					{% endfor %}
				</select>
            </div>

            <label class="col-form-label col-sm-2 font-weight-bold">Năm đi học</label>
            <div class="col-sm-2">
                <input type="number" class="form-control" id="id_studyYear" name="studyYear" min="2000" required />
            </div>
        </div>

        <div class="form-group row">
            <label class="col-form-label col-sm-2 font-weight-bold">Ngày sinh</label>
            <div class="col-sm-4">
                <input type="date" class="form-control" id="id_birthday" name="birthday" required />
            </div>

            <label class="col-form-label col-sm-2 font-weight-bold">Số điện thoại</label>
            <div class="col-sm-4">
                <input type="text" class="form-control" id="id_phone" name="phone" placeholder="+79 54325345..." required />
            </div>
        </div>

        <div class="form-group row">
            <label class="col-form-label col-sm-2 font-weight-bold">Dân tộc</label>
            <div class="col-sm-4">
                <input type="text" class="form-control" id="id_ethnic" name="ethnic" placeholder="Kinh..." required />
            </div>

            <label class="col-form-label col-sm-2 font-weight-bold">Tôn giáo</label>
            <div class="col-sm-4">
                <input type="text" class="form-control" id="id_religion" name="religion" placeholder="Không..." required />
            </div>
        </div>

        <div class="form-group row">
            <label class="col-form-label col-sm-2 font-weight-bold">Địa chỉ VN</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="id_addressVN" name="addressVN" required />
            </div>
        </div>

        <div class="form-group row">
            <label class="col-form-label col-sm-2 font-weight-bold">Địa chỉ Nga</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="id_addressRu" name="addressRu" required />
            </div>
        </div>

        <div class="form-group row">
            <label class="col-form-label col-sm-2 font-weight-bold">Cơ quan công tác (Nếu có)</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="id_workPlace" name="workPlace" />
            </div>
        </div>

        <div class="form-group row">
            <label class="col-form-label col-sm-2 font-weight-bold">Ngày nhập học</label>
            <div class="col-sm-4">
                <input type="date" class="form-control" id="id_dateOfAdmission" name="dateOfAdmission" required />
            </div>

            <label class="col-form-label col-sm-2 font-weight-bold">Ngày bắt đầu khóa học</label>
            <div class="col-sm-4">
                <input type="date" class="form-control" id="id_dateOfStudy" name="dateOfStudy" required />
            </div>
        </div>

        <div class="form-group row">
            <label class="col-form-label col-sm-2 font-weight-bold">Thời gian đào tạo</label>
            <div class="col-sm-4">
                <input type="text" class="form-control" id="id_timeOfStudy" name="timeOfStudy" placeholder="2018-2022" required/>
            </div>

            <label class="col-form-label col-sm-2 font-weight-bold">Kỳ học</label>
            <div class="col-sm-4">
                <input type="text" class="form-control" id="id_infoOfStudy" name="infoOfStudy" placeholder="Học kì 2 - năm 1, còn lại 3 năm" required/>
            </div>
        </div>

        <hr/>

		<div class="text-left">
            <input class="btn btn-primary btn-sm" type="submit" name="submit" value="Save" />
        </div>
	</form>
{% endblock %}